apiVersion: v1
kind: Service
metadata:
  name: {{ template "balance-app.fullname" . }}
  labels:
    app: "{{ template "balance-app.fullname" . }}"
    chart: "{{ template "balance-app.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP | quote }}
  {{- end }}
  ports: {{ .Values.service.ports }}
  selector:
    app: "{{ template "balance-app.fullname" . }}"